# secrets.yaml
apiVersion: v1 # core v1 kubernetes API group
kind: Secret # secret resource type to store passwords, OAuth tokens and SSH keys
metadata:
  name: my-web-app-secrets # name for the secret
type: Opaque # containing key value pairs
data:
  DB_PASSWORD: base64_encoded_password # database password which is base64 encoded, the secret being stored
